from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

from fpdf import FPDF


def slugify_title(raw: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "-", raw).strip("-")
    return safe or "nexaquill-export"


def render_export_markdown(title: str, summary: str, actions: list[str], references: list[dict[str, Any]]) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"_Exported {timestamp}_")
    lines.append("")
    lines.append("## Summary")
    lines.append(summary.strip())
    lines.append("")
    lines.append("## Action items")
    if actions:
        for item in actions:
            lines.append(f"- {item}")
    else:
        lines.append("- None provided")
    if references:
        lines.append("")
        lines.append("## References")
        for ref in references:
            label = ref.get("label") or ref.get("link") or ref.get("type") or "Reference"
            link = ref.get("link")
            if link:
                lines.append(f"- [{label}]({link})")
            else:
                lines.append(f"- {label}")
    lines.append("")
    lines.append("_Generated by NexaQuill_")
    return "\n".join(lines)


def render_export_pdf(title: str, markdown_text: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", style="B", size=14)
    pdf.multi_cell(0, 10, title)
    pdf.ln(2)
    pdf.set_font("Helvetica", size=11)

    for raw_line in markdown_text.splitlines():
        line = raw_line
        if line.startswith("# "):
            pdf.set_font("Helvetica", style="B", size=12)
            pdf.multi_cell(0, 8, line[2:].strip())
            pdf.set_font("Helvetica", size=11)
            continue
        if line.startswith("## "):
            pdf.set_font("Helvetica", style="B", size=11)
            pdf.multi_cell(0, 8, line[3:].strip())
            pdf.set_font("Helvetica", size=11)
            continue
        pdf.multi_cell(0, 8, line or " ")
    raw = pdf.output(dest="S")
    return raw if isinstance(raw, (bytes, bytearray)) else str(raw).encode("latin-1", "replace")
